# Auto-generated browser headers using Camoufox.

BASE_HEADERS = {
 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'accept-encoding': 'gzip, deflate, br, zstd',
 'accept-language': 'en-US,en;q=0.5',
 'cookie': 'userUUID=3b920ab6-34ef-4f25-aa12-a187f58ac076; '
           'contact372d1881-2415-4c85-b076-d77924f8384b="{\'maxNumberContactsAllow\':10}"; '
           'cookieSearch-1="/alquiler-viviendas/madrid-madrid/:1751676018392"; '
           'SESSION=f9959943cee9feb5~372d1881-2415-4c85-b076-d77924f8384b; '
           'datadome=ZAtK8So1S1oJRdYOLkGO0PO_Y_U~I3qjvcHVWnEaZuCU5Uz~mQubSNAbwMQ27YRNaAQzdF58sXNRP9I8fiHHgA0vnaeOK2R3fByxQ7Y1S0OwcfDMBPKk4Fu4HZ45aNSD',
 'sec-fetch-dest': 'document',
 'sec-fetch-mode': 'navigate',
 'sec-fetch-site': 'none',
 'sec-fetch-user': '?1',
 'upgrade-insecure-requests': '1',
 }

# Note: This file is automatically generated and will be overwritten.
