# Auto-generated browser headers using Camoufox.

BASE_HEADERS = \
{'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'accept-encoding': 'gzip, deflate, br, zstd',
 'accept-language': 'en-US,en;q=0.5',
 'cookie': 'userUUID=e88c9753-e969-428b-b8a8-65c0da8af845; '
           'contacta7b33d3a-058a-4797-ab27-95a1192a1429="{\'maxNumberContactsAllow\':10}"; '
           'cookieSearch-1="/alquiler-viviendas/madrid-madrid/:1751696064343"; '
           'SESSION=8a8f644c6188b8b8~a7b33d3a-058a-4797-ab27-95a1192a1429; '
           'datadome=piGEp4dIAp_S5mBPmrqNWzu3aCAglvAsKmfOubN9dMlbI116IQbhivsGoDMsWy5wAr5vaykCvaSw6a1Wk2DYhIrBU0kg_xIV3lGO0QfgW0Fh4IlWBJFTk5clvD4Uxhq8; '
           'didomi_token=eyJ1c2VyX2lkIjoiMTk3ZDkzOGMtNWQ0Ny02ZmM1LTkzODUtYjQ1ZmNhZDc4YTk5IiwiY3JlYXRlZCI6IjIwMjUtMDctMDVUMDY6MTQ6MjYuMDA0WiIsInVwZGF0ZWQiOiIyMDI1LTA3LTA1VDA2OjE0OjI2LjAwNFoiLCJ2ZXJzaW9uIjpudWxsfQ==',
 'sec-fetch-dest': 'document',
 'sec-fetch-mode': 'navigate',
 'sec-fetch-site': 'none',
 'sec-fetch-user': '?1',
 'upgrade-insecure-requests': '1',
 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0'}

# Note: This file is automatically generated and will be overwritten.
